# Generated by Django 6.0.6 on 2026-06-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_is_paid_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='esewa_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pidx',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
