# Generated by Django 6.0.6 on 2026-06-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_orderitem_order_shop_product_shop_suborder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery (COD)'), ('CARD', 'Credit/Debit Card'), ('Esewa', 'eSewa'), ('Khalti', 'Khalti')], default='COD', max_length=100),
        ),
    ]
